language: php

php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"
  - "nightly"

matrix:
  allow_failures:
    - php:
      - "7.4snapshot"
      - "nightly"

script:
  - composer tests

install:
  - travis_retry composer install --no-interaction --prefer-source

after_success:
    - bash <(curl -s https://codecov.io/bash)
