language: php

php:
  - "7.4"
  - "nightly"

matrix:
  allow_failures:
    - php: "nightly"

script:
  - composer tests
  - composer psalm

install:
  - travis_retry composer install --no-interaction --prefer-source

after_success:
    - bash <(curl -s https://codecov.io/bash)
